Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from keras.applications.imagenet_utils import decode_predictions
  File "/usr/local/lib/python3.8/site-packages/keras/__init__.py", line 5, in <module>
    raise ImportError(
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`
