Traceback (most recent call last):
  File "/usr/local/bin/arxiv_latex_cleaner", line 5, in <module>
    from arxiv_latex_cleaner.__main__ import __main__
  File "/usr/local/lib/python3.8/site-packages/arxiv_latex_cleaner/__main__.py", line 26, in <module>
    from .arxiv_latex_cleaner import merge_args_into_config
  File "/usr/local/lib/python3.8/site-packages/arxiv_latex_cleaner/arxiv_latex_cleaner.py", line 25, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
